"""cars table

Revision ID: 60ecd8e74efd
Revises: d1efc9444e1e
Create Date: 2023-12-11 22:53:44.659382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ecd8e74efd'
down_revision = 'd1efc9444e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('VehicleId', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('photo1', sa.LargeBinary(length=4294967295), nullable=True),
    sa.Column('photo2', sa.LargeBinary(length=4294967295), nullable=True),
    sa.Column('PlateNo', sa.String(length=255), nullable=True),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('VehicleId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    # ### end Alembic commands ###
