"""vehicle table

Revision ID: d1efc9444e1e
Revises: d04f643e011c
Create Date: 2023-12-09 20:02:06.694315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1efc9444e1e'
down_revision = 'd04f643e011c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vregister',
    sa.Column('CustomerId', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=255), nullable=True),
    sa.Column('mname', sa.String(length=255), nullable=True),
    sa.Column('lname', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('idpassport', sa.LargeBinary(length=4294967295), nullable=True),
    sa.Column('carreg', sa.LargeBinary(length=4294967295), nullable=True),
    sa.Column('photo1', sa.LargeBinary(length=4294967295), nullable=True),
    sa.Column('photo2', sa.LargeBinary(length=4294967295), nullable=True),
    sa.Column('PlateNo', sa.String(length=255), nullable=True),
    sa.Column('make', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('condition', sa.String(length=255), nullable=True),
    sa.Column('submissionDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('CustomerId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vregister')
    # ### end Alembic commands ###
